name: MsBizzysBBQ
favicon: null
layout_spectrum: 0.25034
typography_spectrum: 0.48865
title: "Ms Bizzy's BBQ"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a213e'
    - '#e4a770'
    - '#c58361'
    - '#a24758'
    - '#faebe2'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
