name: MsBizzysBBQ
favicon: null
layout_spectrum: 0.25034
typography_spectrum: 0.22023858246393502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9d7cb'
    - '#9f937c'
    - '#bab99a'
    - '#522227'
  brandStrength: 0.8125
  lightness: 0.8529201343189925
  saturation: 0.5
  rhythmicContrast: 0.8238632357679307
purpose: []
